defaults:
  - topic
  - override /model@model: test

run_args:
  k:
    - 10
    - 20
    - 30
    - 40
    - 50
    - 60
    - 70
    - 80
    - 90
    - 100
model:
  train_args:
    iterations: 500
  save_full: false
