defaults:
  - topic
  - override /model@model: test

run_args:
  k:
    - 10
task_name: topic-test
model:
  train_args:
    iterations: 50
  save_full: false
  task_name: ${..task_name}
  corpus:
    task_name: ${..task_name}
  batch:
    num_workers: 0
