defaults:
- /plot@wc: wordcloud
_target_: thematos.models.config.WordcloudConfig
_config_name_: wordcloud
_config_group_: /model/plot
top_n: 100
make_collage: true
num_images_per_page: 20
num_cols: 5
num_rows: null
output_file_format: wordcloud_p{page_num:02d}.png
titles: null
title_fontsize: 14
title_color: green
figsize: null
width_multiple: 4
height_multiple: 2
dpi: 300
mask_dir: null
fontpath: null
save: true
