defaults:
- /path@path: __batch__
- /batch@batch: __init__
- /words@wordprior: wordprior
- /dataset@corpus: topic_corpus
- /model/train@train_config: topic
_target_: thematos.models.lda.LdaModel
_config_name_: _lda_
_config_group_: model
verbose: false
task_name: topic
task_root: workspace
version: 0.0.0
module: null
pipelines: []
batch_name: batch
model_type: LDA
coherence_metric_list:
- u_mass
- c_uci
- c_npmi
- c_v
eval_coherence: false
set_wordprior: false
save: true
save_full: true
