defaults:
- /path@path: __batch__
- /batch@batch: __init__
- /words@wordprior: wordprior
- /dataset@corpus: topic_corpus
- /model/config@model_args: lda
- /model/train@train_args: topic
_target_: thematos.models.base.TopicModel
_config_name_: topic
_config_group_: model
verbose: false
task_name: topic
task_root: workspace
version: 0.0.0
module: null
pipelines: []
batch_name: model
model_type: BASE
coherence_metric_list:
- u_mass
- c_uci
- c_npmi
- c_v
eval_coherence: false
set_wordprior: false
autosave: true
save_full: true
